apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipebook-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: recipebook-ui-service
                port:
                  number: 80
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: recipebook-api-service
                port:
                  number: 9000